// se_pass/src/components/Login/Login.vue
<template>
<div class="container">
    	<div class="row">
			<div class="col-md-6 col-md-offset-3">
				<div class="panel panel-login">
					<div class="panel-body">
						<div class="row">
							<div class="col-lg-12">
								<form id="login-form" role="form" style="display: block;" v-on:submit.prevent="login">
									<div class="form-group">
										<input type="text" name="username" id="username" tabindex="1" class="form-control" placeholder="Account" value="" v-model="account">
									</div>
									<div class="form-group">
										<input type="password" name="password" id="password" tabindex="2" class="form-control" placeholder="Password" v-model="password">
									</div>
									<!-- <div class="form-group text-center">
										<input type="checkbox" tabindex="3" class="" name="remember" id="remember">
										<label for="remember"> Remember Me</label>
									</div> -->
									<div class="form-group">
										<div class="row">
											<div class="col-sm-6 col-sm-offset-3">
												<button name="login-submit" id="login-submit" tabindex="4" class="form-control btn btn-login" data-loading-text="<i class='fa fa-circle-o-notch fa-spin' ></i> 登入中">Log In</button>
											</div>
										</div>
									</div>
									<!-- <div class="form-group">
										<div class="row">
											<div class="col-lg-12">
												<div class="text-center">
													<a href="https://phpoll.com/recover" tabindex="5" class="forgot-password">Forgot Password?</a>
												</div>
											</div>
										</div> -->
									<!-- </div> -->
								</form>
							</div>
						</div>
					</div>
				</div>
			</div>
			</div>
</div>
</template>

<script>
let template
export default{
  data () {
    return {
      account: '',
      password: ''
    }
  },
  mount () {
    template = this
  },
  methods: {
    login () {
      template.$router.push({
        path: '/app'
      })
    }
  }
}
</script>

// Team3_React_PASS/src/views/Login/Login.jsx
import React, { Component } from 'react';
import ChartistGraph from 'react-chartist';
import Link from 'react-router'
import { Grid, Row, Col, Form, FormGroup, InputGroup ,FormControl, Button} from 'react-bootstrap';
import book from './books-1316306_960_720.png';
import allPass from './allPass.png'
import  './Login.css';


class Login extends Component {
  render(){
    return (
      <div className="content" >
          <div style={{
            alignItems:'center',
            justifyContent:'center',
            display:'flex',
          }}>
	        	<img src={book} style={{
              width:'40%',
              height:'40%',
              }}></img>
          </div>
          <div style={{
              alignItems:'center',
              justifyContent:'center',
              display:'flex',
            }}>
		        <img src={allPass}></img>
           </div>
           <Row>
             <Col md={6} mdOffset={3}>
             <div className={"panel panel-login"}>
				    	<div className={"panel-body"}>
                  <Row>
                    <Col lg={12}>
                    <Form id="login-form"  role="form" style={{
                      display: 'block'
                      }} >
                      <FormGroup>
                          <FormControl type="text" name="username" id="username" className={"form-control"} placeholder="Account"/> 
                      </FormGroup>
                      <FormGroup>
                          <FormControl type="password" name="password" id="password" className={"form-control"} placeholder="Password"/> 
                      </FormGroup>
                      <FormGroup>
                        <Row>
                          <Col sm={6} smOffset={3}>
                            <Button className={"form-control btn btn-login"} href={"#/app"}>登入</Button>
                          </Col>
                        </Row>
                      </FormGroup>
                    </Form>
                    </Col>
                  </Row>
              </div>
            </div>
            </Col>
           </Row>
      </div>
    );
  }
}
export default Login;
